services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${DB_USER}
      RABBITMQ_DEFAULT_PASS: ${DB_PASS}

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${RABBITMQ_USER}
      POSTGRES_PASSWORD: ${RABBITMQ_PASS}
      POSTGRES_DB: notification_db
